# Generated by Django 3.2.8 on 2021-10-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
